version: 7
profiles: []
groups: []
configSync:
  parts: {}
hotkeys:
  toggle-window: []
  copy-current-path: []
  ctrl-c:
    - Ctrl-C
  copy:
    - ⌘-C
  paste:
    - ⌘-V
  clear:
    - ⌘-K
  select-all:
    - ⌘-A
  zoom-in:
    - ⌘-=
    - ⌘-Shift-=
  zoom-out:
    - ⌘--
    - ⌘-Shift--
  reset-zoom:
    - ⌘-0
  home:
    - ⌘-Left
    - Home
  end:
    - ⌘-Right
    - End
  previous-word:
    - ⌥-Left
  next-word:
    - ⌥-Right
  delete-previous-word:
    - ⌥-Backspace
  delete-line:
    - ⌘-Backspace
  delete-next-word:
    - ⌥-Delete
  search:
    - ⌘-F
  pane-focus-all:
    - ⌘-Shift-I
  focus-all-tabs:
    - ⌘-⌥-Shift-I
  scroll-to-top:
    - - G
      - G
  scroll-page-up: []
  scroll-up: []
  scroll-down: []
  scroll-page-down: []
  scroll-to-bottom:
    - Shift-G
  restart-telnet-session: []
  restart-ssh-session: []
  launch-winscp: []
  settings-tab: {}
  settings:
    - ⌘-,
  serial:
    - Alt-K
  restart-serial-session: []
  new-tab:
    - ⌘-T
  new-window:
    - ⌘-N
  profile: {}
  profile-selectors: {}
  group-selectors: {}
  toggle-fullscreen: []
  close-tab:
    - ⌘-Shift-W
  reopen-tab:
    - ⌘-Shift-T
  toggle-last-tab: []
  rename-tab:
    - ⌘-R
  next-tab:
    - ⌘-Shift-]
  previous-tab:
    - ⌘-Shift-[
  move-tab-left: []
  move-tab-right: []
  rearrange-panes: []
  tab-1:
    - ⌘-1
  tab-2:
    - ⌘-2
  tab-3: []
  tab-4: []
  tab-5: []
  tab-6: []
  tab-7: []
  tab-8: []
  tab-9: []
  tab-10: []
  duplicate-tab: []
  restart-tab: []
  reconnect-tab: []
  disconnect-tab: []
  explode-tab:
    - ⌘-Shift-.
  combine-tabs:
    - ⌘-Shift-,
  tab-11: []
  tab-12: []
  tab-13: []
  tab-14: []
  tab-15: []
  tab-16: []
  tab-17: []
  tab-18: []
  tab-19: []
  tab-20: []
  split-right:
    - ⌘-D
  split-bottom:
    - ⌘-Shift-D
  split-left: []
  split-top: []
  pane-nav-right:
    - ⌘-⌥-Right
  pane-nav-down:
    - ⌘-⌥-Down
  pane-nav-up:
    - ⌘-⌥-Up
  pane-nav-left:
    - ⌘-⌥-Left
  pane-nav-previous:
    - ⌘-⌥-[
  pane-nav-next:
    - ⌘-⌥-]
  pane-nav-1: []
  pane-nav-2: []
  pane-nav-3: []
  pane-nav-4: []
  pane-nav-5: []
  pane-nav-6: []
  pane-nav-7: []
  pane-nav-8: []
  pane-nav-9: []
  pane-maximize:
    - ⌘-⌥-Enter
  close-pane:
    - ⌘-W
  pane-increase-vertical: []
  pane-decrease-vertical: []
  pane-increase-horizontal: []
  pane-decrease-horizontal: []
  profile-selector:
    - ⌘-E
  switch-profile:
    - ⌘-Shift-E
  command-selector:
    - ⌘-Shift-P
terminal:
  searchOptions:
    caseSensitive: true
  colorScheme:
    name: Bright Lights
    foreground: '#b3c9d7'
    background: '#191919'
    cursor: '#f34b00'
    colors:
      - '#191919'
      - '#ff355b'
      - '#b7e876'
      - '#ffc251'
      - '#76d4ff'
      - '#ba76e7'
      - '#6cbfb5'
      - '#c2c8d7'
      - '#191919'
      - '#ff355b'
      - '#b7e876'
      - '#ffc251'
      - '#76d5ff'
      - '#ba76e7'
      - '#6cbfb5'
      - '#c2c8d7'
  customColorSchemes: []
  font: JetBrainsMono Nerd Font
  copyOnSelect: true
  bell: visual
ssh: {}
clickableLinks: {}
accessibility: {}
appearance: {}
hacks: {}
providerBlacklist: []
commandBlacklist: []
enableAnalytics: false
enableWelcomeTab: false
pluginBlacklist: []
profileBlacklist: []
profileDefaults:
  ssh:
    disableDynamicTitle: true
highlightPlugin:
  advanced: {}
  highlightProfiles:
    - id: 60606be0-c0ff-42bc-bf77-de8a2435447f
      name: Default
      keywords:
        - text: ERROR
          enabled: true
          background: true
          backgroundColor: '1'
        - text: WARN
          enabled: true
          background: true
          backgroundColor: '3'
        - text: INFO
          enabled: true
          background: true
          backgroundColor: '6'
        - text: 错误
          enabled: true
          background: true
          backgroundColor: '1'
        - text: 警告
          enabled: true
          background: true
          backgroundColor: '3'
        - text: 信息
          enabled: true
          background: true
          backgroundColor: '6'
  replaceProfiles:
    - id: 986666dd-dac9-4c7a-a295-9b4aff66abdd
      name: Default
      patterns:
        - enabled: true
          search: ERROR
          replace: 出错啦
        - enabled: true
          search: WARN
          replace: 警告警告
